### ISSUE TITLE
Not finding tests folder

### ISSUE THREAD

**Issue by schungx** [swellaby/vscode-rust-test-adapter#99] opened 2021-03-22 05:22 UTC
`project/tests/*` - not found in Test Explorer

`project/src/tests/*` - found in Test Explorer.

I believe that the official location for `tests` is the same level as `src`, not under `src`...

**Comment by calebcartwright** [comment] 2021-03-23 00:54
hi, thanks for reaching out but I am going to close this as a duplicate of several prior issues, and encourage you to subscribe to #3 if you're interested in status updates on support for integration tests.

> I believe that the official location for tests is the same level as src, not under src...

That's not correct. Those two top level directories are used to differentiate different types of tests, with what are typically referred to as "unit" tests going under `src` and "integration" tests going under `tests`, and cargo issuing different rustc invocations for compiling, linking, and execution. Neither is more or less official than the other, just different types of tests.

In order to properly discover, load, and execute th

**Closed by calebcartwright** 2021-03-23 00:54 UTC
