### ISSUE TITLE
List Doctests

### ISSUE THREAD

**Issue by laralove143** [swellaby/vscode-rust-test-adapter#260] opened 2022-09-02 15:45 UTC
Currently only explicit tests are listed, but the default behavior of `cargo test` is to run Doctests (codeblocks in docs unless they start with ```ignore) as well, so they should be listed in the tree

**Comment by calebcartwright** [comment] 2022-09-04 22:54
Closing as a duplicate of #4

**Closed by calebcartwright** 2022-09-04 22:54 UTC
Labels: duplicate
