### ISSUE TITLE
Still broken

### ISSUE THREAD

**Issue by Yuri6037** [swellaby/vscode-rust-test-adapter#251] opened 2022-08-12 15:02 UTC
This extension never worked in any of my projects. I tried this a few months ago but no tests were visible, I just thought this was a bug.

I just tried today again and exact same thing, the exact same bug is still not fixed...

# How to reproduce
- Get Kubuntu,
- Get vscode through snap (proprietary license),
- Install rust-analyzer, codelldb and this extension,
- Open "Konsole" type "git clone https://gitlab.com/bp3d/bpx/bpx-rs",
- Make sure you're on "develop" branch or type "git checkout develop",
- Open vscode in the newly cloned bpx-rs repository,
- Enjoy no tests listed in the test explorer tab.

There should be at least 45 doc tests, 2 integration tests and 6 unit tests (there could be more when you clone it because I'm developing this library); currently NONE are listed!

**Comment by calebcartwright** [comment] 2022-09-04 23:08
Thank you for using the extension and reaching out!

In short, your report is a duplicate of several others and so I'm going to close.

* Integration tests have never been supported - #3 
* Doc tests have never been supported - #4 
* All of your unit tests require features to be enabled (e.g. compare the output of `cargo test -- --list` with `cargo test --all-features -- --list` in your project), but this extension never had support for feature-toggled tests - #95

Additionally, we haven't really been working on enhancing this extension for quite some time because work has been underway to incorporate the same capabilities natively into Rust Analyzer. We're still doing a bit of maintenance and are happy to review any community submitted PRs that fix bugs and/or add new features, but it's unlikely we'll be adding any new features ourselves unless the RA team decides to abandon their plans.

Finally, and just my two cents, but in the future I would encourage you to reach out with reports at the time an issue is experienced. Not reporting an issue and just assuming it will somehow be discovered and fixed isn't necessarily a great strategy for resolving issues.

**Closed by calebcartwright** 2022-09-04 23:08 UTC
Labels: duplicate
